### ISSUE TITLE
Missing build for ARM/ARM64

### ISSUE THREAD

**Issue by dominikfladung** [biigle/pgvector#1]
To run biigle on a M1 MacBook Pro, the ARM build of this container is required.

Currently, the image must be built locally.

**Comment by mzur** [comment]
It looks like ARM is only available with [larger runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners) which are not included in our free plan. So we can't support ARM builds as part of our GH actions. While there also is the "official" ankane/pgvector image, it's 2x the size of ours. So I think we have to stick with the current situation and ARM users have to build the images themselves for now.

**Comment by dlangenk** [comment]
You can also change the architecture in the docker file to always use x86 and the M1 will emulate that which is sufficiently fast enough.

**Comment by mzur** [comment]
Can you give an example how to specify the architecture?

**Comment by dlangenk** [comment]
I am not 100% sure, but 95% that you just have to set "platform: linux/amd64" in docker-compose.yml for each image. Or when building use DOCKER_DEFAULT_PLATFORM=linux/amd64 docker-compose build
